### ISSUE TITLE
Novel view synthesis performance

### ISSUE THREAD

**Issue by Beniko95J** [EnVision-Research/Ref-NeuS#2]
Hi, I have tried to test the performance of the released pretrained model, but I cannot get the PSNRs reported in Tab.3 in the paper (e.g., 14 vs 27 on the toaster scene in Tab.3). Here are the rendered images I got

<img width="487" alt="Screenshot 2023-08-16 at 17 29 26" src="https://github.com/EnVision-Research/Ref-NeuS/assets/30772597/0b9af102-3826-48bc-945d-7be060cd20ea">

Could you help me about this? I got the results by running 

```
python exp_runner.py --mode validate_mesh --conf ./confs/womask.conf --ckpt_path ckpt_path --validate_normal
```

Also, I am wondering which images (200 images for training or the left 100 images) are used for getting the numbers in Tab.3.

Thanks

**Comment by g3956** [comment]
There are some differences of the setting between novel view synthesis and reconstruction task. 

To get the PSNRs reported in the paper, please refer to this link for the pretrained models https://drive.google.com/file/d/1wqFJBv3hAHbBTM49yQZ_Gctm2CV_QVrr/view?usp=sharing

**Comment by Beniko95J** [comment]
Hi, I still have problems reproducing the novel view synthesis results using the given render models. I think the problem maybe in this [line](https://github.com/EnVision-Research/Ref-NeuS/blob/29defb441133f1ba2097b6cf3b812e19c8da93ab/models/renderer.py#L241), where you still use the view direction as color network inputs, which is different from the paper.

Hope for a reply!

**Comment by g3956** [comment]
Since the training code has not been released, this also affects the evaluation of novel view synthesis.

In this case, I have updated the view conditions for the color network. You can test it again by running the following command:
```
python exp_runner.py --mode validate_mesh --conf ./confs/womask.conf --ckpt_path ckpt_path --validate_normal
```

I hope this is helpful.
