### ISSUE TITLE
How to evaluate the MAE？

### ISSUE THREAD

**Issue by qianqjia** [EnVision-Research/Ref-NeuS#9]
Thanks for the wonderful work. I'm wondering know how to evaluate the value of MAE, and can you provide reference code. thanks~

**Comment by g3956** [comment]
Hi, thanks for your interest in our work.
I provided the code for MAE computation in Line 437 of the [file](https://github.com/EnVision-Research/Ref-NeuS/blob/main/exp_runner.py)
